const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getLibrary: () => ipcRenderer.invoke('library:get'),
  rescan: () => ipcRenderer.invoke('library:rescan'),
  addFolder: () => ipcRenderer.invoke('library:addFolder'),
  removeFolder: (folder) => ipcRenderer.invoke('library:removeFolder', folder),
  getConfig: () => ipcRenderer.invoke('config:get'),
  setVlcPath: () => ipcRenderer.invoke('config:setVlcPath'),
  setTmdbKey: (key) => ipcRenderer.invoke('config:setTmdbKey', key),
  fetchAllMeta: () => ipcRenderer.invoke('meta:fetchAll'),
  fetchAllImdb: () => ipcRenderer.invoke('imdb:fetchAll'),
  onImdbProgress: (cb) => ipcRenderer.on('imdb:progress', (_e, data) => cb(data)),
  clearMeta: () => ipcRenderer.invoke('meta:clear'),
  searchMeta: (query, type) => ipcRenderer.invoke('meta:search', query, type),
  applyMeta: (itemTitle, itemType, tmdbId, mediaType, rawTitle, folder) => ipcRenderer.invoke('meta:apply', itemTitle, itemType, tmdbId, mediaType, rawTitle, folder),
  resetCache: () => ipcRenderer.invoke('library:resetCache'),
  onMetaProgress: (cb) => ipcRenderer.on('meta:progress', (_e, data) => cb(data)),
  getProgress: () => ipcRenderer.invoke('progress:get'),
  clearProgress: (p) => ipcRenderer.invoke('progress:clear', p),
  getHistory: () => ipcRenderer.invoke('history:get'),
  clearHistory: () => ipcRenderer.invoke('history:clear'),
  play: (p) => ipcRenderer.invoke('play', p),
  openFolder: (p) => ipcRenderer.invoke('shell:openFolder', p),
  openExternal: (url) => ipcRenderer.invoke('shell:openExternal', url),
  getTrending: () => ipcRenderer.invoke('discover:trending'),
  readImage: (p) => ipcRenderer.invoke('image:read', p),
  // Player embutido / toggles
  getSidecars: (p) => ipcRenderer.invoke('player:sidecars', p),
  saveProgress: (p, time, length) => ipcRenderer.invoke('progress:save', p, time, length),
  logOpen: (p) => ipcRenderer.invoke('history:logOpen', p),
  logClose: (p) => ipcRenderer.invoke('history:logClose', p),
  setToggle: (key, value) => ipcRenderer.invoke('config:setToggle', key, value),
  setNumber: (key, value) => ipcRenderer.invoke('config:setNumber', key, value),
});
